### PR TITLE
Request adopisowifi

### PR DESCRIPTION
**Pull request by danpoon84**
requesting for full instruction on installing adopisowifi without license verification (from the very beginning)

### CODE REVIEW

**Comment by adonespitogo** [comment]
There is no such thing without license. This is the repository for web portal only.

**Comment by quinxx23** [comment]
danpoon84 message me ihave no license software created..

**Comment by danpoon84** [comment]
Hi quinxx23, How?

**Comment by danpoon84** [comment]
what is your email?

**Pull request closed without merging**
